export interface SecurityConfig {
  SECURITY_PROMPT_ENABLED?: boolean;
  SECURITY_PROMPT_THRESHOLD?: number;
  SECURITY_PROMPT_CLASSIFIER_ENABLED?: boolean;
  SECURITY_PROMPT_CLASSIFIER_MODEL?: string;
  SECURITY_PROMPT_CLASSIFIER_ENDPOINT?: string;
  SECURITY_PROMPT_CLASSIFIER_TOKEN?: string;
  SECURITY_COMMAND_CLASSIFIER_ENABLED?: boolean;
  SECURITY_COMMAND_CLASSIFIER_ENDPOINT?: string;
  SECURITY_COMMAND_CLASSIFIER_TOKEN?: string;
}
